import { GetStaticProps, NextPage, GetStaticPaths } from 'next';
import { getCharacter, getCharacters } from "dh-marvel/services/marvel/marvel.service";
import Head from 'next/head';
import BodySingle from 'dh-marvel/components/layouts/body/single/body-single';
import { CardCharacter } from 'dh-marvel/components/ui/cardCharacter/CardCharacter';

interface Props {
	character: any
    id: number|string
}

const CharacterPage:NextPage<Props> = ({character, id}) => {    
   
	return (   
        <>
        <Head>
            <title>DH-Marvel Store</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <BodySingle title={"Detalle"}>
					    <CardCharacter data={character} />
             </BodySingle>   
           
        </>
    );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const data: any = await getCharacters();

  const paths = data.map((character: any) => {
    return { params: { id: character.id.toString() } };
  });

  return {
    paths,
    fallback: true,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const id = parseInt(params?.id as string);
  const character = await getCharacter(id);

  return {
    props: {
      character
    },
    revalidate: 10,
  };
};





export default CharacterPage;