import {  GetServerSideProps, NextPage} from 'next';
import Head from 'next/head';
import BodySingle from 'dh-marvel/components/layouts/body/single/body-single';
import { getCharacter, getComic } from 'dh-marvel/services/marvel/marvel.service';
import { CardPanel } from 'dh-marvel/components/ui/cardPanel/CardPanel';
import { Comic } from 'dh-marvel/features/marvel/comic.types';
import { useRouter } from 'next/router';
import { Button } from '@mui/material';

interface Props{
    comic: Comic
    id: number
}

const ConfirmationOrder:NextPage<Props>= ({comic, id}) => {    
   
    const router= useRouter()

	const handelVolver = () => {  
        localStorage.removeItem("usuario")
        router.push('/');   
};

	return (   
        <>
        <Head>
            <title>DH-Marvel Store</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <BodySingle title={"Gracias por su compra!!"}>
					    <CardPanel data={comic} />
                        <Button onClick={handelVolver} size="small" variant="contained" >Volver </Button>
            </BodySingle>   
           
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
    const id = Number(context.params?.id)
    const data = await getComic(id);
    return {
     props:{
      comic:data,
      id
     }
    };
  };
  

export default ConfirmationOrder;


